version: '3.8'

services:
  server:
    image: novitix/canvas-server
    container_name: canvas-server
    ports:
      - "1234:1234"
  client:
    image: novitix/canvas-client
    container_name: canvas-client
    ports:
      - "3000:3000"
    volumes:
      - type: bind
      - source: /work/config.json
      - target: /app
volumes:
  config:
  