version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: canvas-server
    ports:
      - "80:80"
    command: ./server
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: canvas-client
    ports:
      - "3000:3000"
    volumes:
      - config:/app/config