name: Docker Image CI & Push to Docker Hub

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend
        run: |
          docker buildx build --build-arg "${{ vars.VITE_API_URL }}" --platform linux/arm64 -t novitix/canvas-client:latest ./client --output=type=registry

      - name: Build and Push Backend
        run: |
          docker buildx build --platform linux/arm64 -t novitix/canvas-server:latest ./server --output=type=registry

      # - name: SSH into VPS and deploy
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
      #     chmod 600 ~/.ssh/id_ed25519
      #     ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      #     ssh -i ~/.ssh/id_ed25519 user@${{ secrets.VPS_HOST }} << 'EOF'
      #       cd /path/to/docker-compose
      #       docker compose pull
      #       docker compose up -d
      #     EOF
